- name: Install App Managers
  hosts: myhosts
  tasks:
    - name: Install flatpak
      become: true
      ansible.builtin.apt:
        name: flatpak
        state: present

    - name: Configure flatpak
      community.general.flatpak_remote:
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user
        name: flathub
        state: present

    - name: Install Luarocks
      community.general.homebrew:
        name: luarocks
        state: present

    - name: Install Node Version Manager (NVM)
      ansible.builtin.shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

    - name: Install SDKMan
      ansible.builtin.shell: |
        curl -o- https://get.sdkman.io?rcupdate=false | bash
      args:
        creates: "{{ ansible_env.HOME }}/.local/bin/sdkman/bin/sdkman-init.sh"

    - name: Install snapd
      become: true
      ansible.builtin.apt:
        name: snapd
        state: present

- name: Install Development Tools
  hosts: myhosts
  tasks:
    - name: Install CMake
      community.general.homebrew:
        name: cmake
        state: present

    - name: Install gh
      community.general.homebrew:
        name: gh
        state: present

    - name: Install llvm
      community.general.homebrew:
        name: llvm
        state: present

    - name: Install Love
      ansible.builtin.uri:
        url: https://github.com/love2d/love/releases/download/11.5/love-11.5-x86_64.AppImage
        dest: "{{ ansible_env.HOME }}/.local/bin/love"
        creates: "{{ ansible_env.HOME }}/.local/bin/love"
        mode: u+rwx

    - name: Install Lua 5.4.7
      community.general.homebrew:
        name: lua@5.4
        state: present

    - name: Install Lua Language Server
      community.general.homebrew:
        name: lua-language-server
        state: present

    - name: Install NeoVim
      community.general.homebrew:
        name: neovim
        state: present

    - name: Install Node v22.12.0
      ansible.builtin.shell: |
        . "{{ ansible_env.HOME }}/.nvm/nvm.sh"
        nvm install 22.12.0
        nvm use 22.12.0

    - name: Install Pre-Commit
      community.general.homebrew:
        name: pre-commit
        state: present

    - name: Install Python 3.10
      community.general.homebrew:
        name: python@3.10
        state: present

    - name: Install OpenSSH Client
      become: true
      ansible.builtin.apt:
        name: openssh-client
        state: present

    - name: Install Stow
      community.general.homebrew:
        name: stow
        state: present

    - name: Install tmux
      community.general.homebrew:
        name: tmux
        state: present

- name: Install Flatpak Apps
  hosts: myhosts
  tasks:
    - name: Install Firefox
      community.general.flatpak:
        method: user
        remote: flathub
        name: org.mozilla.firefox
        state: present

    - name: Install Kooha
      community.general.flatpak:
        method: user
        remote: flathub
        name: io.github.seadve.Kooha
        state: present

    - name: Install LibreOffice
      community.general.flatpak:
        method: user
        remote: flathub
        name: org.libreoffice.LibreOffice
        state: present

    - name: Install Obsidian
      community.general.flatpak:
        method: user
        remote: flathub
        name: md.obsidian.Obsidian
        state: present

    - name: Install Parsec
      community.general.flatpak:
        method: user
        remote: flathub
        name: com.parsecgaming.parsec
        state: present

    - name: Install Zoom
      community.general.flatpak:
        method: user
        remote: flathub
        name: us.zoom.Zoom
        state: present

    - name: Install Zotero
      community.general.flatpak:
        method: user
        remote: flathub
        name: org.zotero.Zotero
        state: present

- name: Install Snap Apps
  hosts: myhosts
  tasks:
    - name: Install Chromium
      become: true
      community.general.snap:
        name: chromium
        state: present

    - name: Install VLC
      become: true
      community.general.snap:
        name: vlc
        state: present

- name: Install TLA+ Toolkit 1.7.4
  hosts: myhosts
  tasks:
    - name: Check If TLA+ Toolkit Is Installed
      register: TLA_INSTALLED
      ignore_errors: true
      ansible.builtin.shell:
        cmd: ls /opt/TLA+Toolbox

    - name: Download TLA+ Toolkit Is Installed
      when: TLA_INSTALLED["rc"] != 0
      ansible.builtin.uri:
        dest: /tmp/tla.deb
        mode: u+rwx
        url: https://github.com/tlaplus/tlaplus/releases/download/v1.7.4/TLAToolbox-1.7.4.deb

    - name: Install TLA+ Toolkit
      when: TLA_INSTALLED["rc"] != 0
      become: true
      ansible.builtin.apt:
        deb: /tmp/tla.deb

- name: Install VirtualBox
  hosts: myhosts
  tasks:
    - name: Check If VirtualBox Is Installed
      register: VBOX_INSTALLED
      ignore_errors: true
      ansible.builtin.shell:
        cmd: which virtualbox

    - name: Download VirtualBox
      when: VBOX_INSTALLED["rc"] != 0
      ansible.builtin.uri:
        dest: /tmp/vbox.deb
        mode: u+rwx
        url: https://download.virtualbox.org/virtualbox/7.1.4/virtualbox-7.1_7.1.4-165100~Ubuntu~jammy_amd64.deb

    - name: Install VirtualBox
      when: VBOX_INSTALLED["rc"] != 0
      become: true
      ansible.builtin.apt:
        deb: /tmp/vbox.deb

- name: Install Tailscale
  hosts: myhosts
  become: true
  tasks:
    - name: Download Tailscale GPG Key
      ansible.builtin.uri:
        dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
        url: https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg
        creates: /usr/share/keyrings/tailscale-archive-keyring.gpg

    - name: Add Tailscale repository
      ansible.builtin.uri:
        dest: /etc/apt/sources.list.d/tailscale.list
        url: https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscale-keyring.list
        creates: /etc/apt/sources.list.d/tailscale.list

    - name: Install Tailscale
      ansible.builtin.apt:
        name: tailscale
        update_cache: true
        state: present
